### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by WhiteCat6142** [shingetsu/saku#14]
https://github.com/shingetsu/saku/blob/72589676cb013cec0ef87a10196116c6a1899689/shingetsu/server_cgi.py#L152

appendがないのはバグでしょうか？
ヤバめに見える割には致命的な問題が起きていないような

**Comment by fuktommy** [comment]
そんな気がしますね。
修正しました。
0e5122fd55755456faa78eb580202aff3eca0482
